Update ipfs.yml

diff --git a/.github/workflows/ipfs.yml b/.github/workflows/ipfs.yml
--- a/.github/workflows/ipfs.yml
+++ b/.github/workflows/ipfs.yml
@@ -29,57 +29,25 @@ jobs:
         with:
           files_yaml: |
             json: socializing-pool-merkle/**
-        # run: |
-        #   git diff --name-only main~1 main 
-# | grep "socializing-pool-merkle/" >> $GITHUB_OUTPUT
         id: changed-files-yaml
         
       - name: Run step if test file(s) change
-        if: steps.changed-files-yaml.outputs.json_any_changed == 'true'  
+        if: steps.changed-files-yaml.outputs.all_changed_files_count != '1'
         run: |
-          echo "One or more test file(s) has changed."
+          echo "ERROR: more than one file changed."
           echo "List all the files that have changed: ${{ steps.changed-files-yaml.outputs.json_all_changed_files }}"
-      
-      # - name: Upload to IPFS
-      #   # You may pin to the exact commit or the version.
-      #   # uses: aquiladev/ipfs-action@12cc5d253735dc2894fe19828bd042c8532acc5d
-      #   uses: aquiladev/ipfs-action@v0.3.1
-      #   with:
-      #     # Directory path to upload
-      #     path: ${steps.fetch_updated_files.outputs}
-      #     # Pin object when adding
-      #     # pin: # optional, default is true
-      #     # Human name for pin
-      #     # pinName: # optional
-      #     # Type of target service to upload. Supported services [ipfs, pinata, infura, filebase]
-      #     service: infura # optional, default is ipfs
-      #     # [infura] Project ID. Required for infura service
-      #     infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }} # optional
-      #     # [infura] Project Secret. Required for infura service
-      #     infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }} # optional
-      #     # Request timeout
-      #     # timeout: # optional, default is 60000
-      #     # Level of verbosity
-      #     # verbose: # optional
-      #     # [ipfs] IPFS host
-      #     # host: # optional, default is ipfs.io
-      #     # [ipfs] IPFS port
-      #     # port: # optional, default is 5001
-      #     # [ipfs] IPFS protocol
-      #     # protocol: # optional, default is https
-      #     # [ipfs] IPFS headers as json object
-      #     # headers: # optional, default is {}
-      #     # [ipfs] IPNS key name. IPNS key will be published when the key parameter is provided. The key will be created if it does not exist
-      #     # key: # optional
-      #     # [pinata] API Key. Required for pinata service
-      #     # pinataKey: # optional
-      #     # [pinata] Secret Key. Required for pinata service
-      #     # pinataSecret: # optional
-      #     # [pinata] Human name for pin
-      #     # pinataPinName: # optional
-      #     # [filebase] Bucket Name. Required for Filebase service
-      #     # filebaseBucket: # optional
-      #     # [filebase] Api Key. Required for Filebase service
-      #     # filebaseKey: # optional
-      #     # [filebase] Secret Api Key. Required for Filebase service
-      #     # filebaseSecret: # optional
+          exit 1
+      - name: Upload to IPFS
+        # You may pin to the exact commit or the version.
+        # uses: aquiladev/ipfs-action@12cc5d253735dc2894fe19828bd042c8532acc5d
+        uses: aquiladev/ipfs-action@v0.3.1
+        with:
+          # Directory path to upload
+          path: ${steps.fetch_updated_files.outputs}
+          # Type of target service to upload. Supported services [ipfs, pinata, infura, filebase]
+          service: infura # optional, default is ipfs
+          # [infura] Project ID. Required for infura service
+          infuraProjectId: ${{ secrets.INFURA_PROJECT_ID }} # optional
+          # [infura] Project Secret. Required for infura service
+          infuraProjectSecret: ${{ secrets.INFURA_PROJECT_SECRET }} # optional
+
